Implementation/branches/MemeMVC/MemeMVC/Controllers/MemeMVC/NoteController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using Ninject;
using Base;
using Base.Model.DTO;
using Base.ViewModel;
using MemeMVC.Model.DTO;
using MemeMVC.Service;
using MemeMVC.ViewModel;
namespace MemeMVC.Controllers
{
    public class NoteController : BaseController
    {
        INoteService _noteService;
        public NoteController()
        {
        }
        [Inject]
        public NoteController(INoteService noteService)
        {
            _noteService = noteService;
        }
        #region Normal Action
        public ActionResult Admin()
        {
            return View();
        }
        #endregion
        public ActionResult Detail(int id)
        {
            ViewBag.NoteID = id;
            return View();
        }
        public ActionResult Edit(int id)
        {
            ViewBag.NoteID = id;
            return View();
        }
        public ActionResult Create()
        {
            return View();
        }
        #region Ajax Action
        [AllowAnonymous]
        [HttpPost]
        public JsonResult Get(int? id)
        {
            HttpStatusCode hCode;
            NoteViewModel mv = new NoteViewModel();
            if (id == null || id == 0)
            {
                mv.Result = Base.ViewModel.ResultType.Success;
                mv.Note = new NoteDTO();
                return Json(mv);
            }
            else
            {
                mv.Note = _noteService.Get(id.Value, out hCode);
                if (hCode != HttpStatusCode.OK)
                {
                    mv.Result = Base.ViewModel.ResultType.Unsuccess;
                }
            }
            mv.Result = Base.ViewModel.ResultType.Success;
            return Json(mv);
        }
        [AllowAnonymous]
        [HttpPost]
        public JsonResult Gets(List<SearchParam> searchparams)
        {
            HttpStatusCode hCode;
            NotesViewModel mv = new NotesViewModel();
            List<AddedParam> param = new List<AddedParam>();

            bool isLinkedInMap = false;
            if (searchparams != null && searchparams.Count > 0)
            {
                foreach (var sparam in searchparams)
                {
                    AddedParam aparam = new AddedParam();
                    aparam.Key = sparam.Key;
                    aparam.Value = sparam.Value;
                    param.Add(aparam);
                    if (sparam.Key == "MapID" && Convert.ToInt32(sparam.Value) == 0)
                    {
                        isLinkedInMap = true;
                    }
                }
            }
            if (!isLinkedInMap)
            {
                mv.Notes = _noteService.GetMany(param, out hCode).ToList();
            }
            else
            {
                hCode = HttpStatusCode.OK;
                if (Session["LinkedInNotes"] != null)
                {
                    mv.Notes = new List<NoteDTO>();
                    foreach (NoteLinkedInDTO note in (List<NoteLinkedInDTO>)Session["LinkedInNotes"])
                    {
                        NoteDTO newnote = new NoteDTO();
                        newnote.Body = note.Body;
                        newnote.RID = note.RID;
                        newnote.MapID = note.MapID;
                        newnote.NoteID = note.NoteID;
                        mv.Notes.Add(newnote);
                    }
                }
                else
                {
                    mv.Notes = new List<NoteDTO>();
                }
            }
            if (hCode != HttpStatusCode.OK)
            {
                mv.Result = Base.ViewModel.ResultType.Unsuccess;
                return Json(mv);
            }
            mv.Result = Base.ViewModel.ResultType.Success;
            return Json(mv);
        }
        [AllowAnonymous]
        [HttpPost]
        public JsonResult GetPage(int? pageindex, int? pagesize, List<SearchParam> searchparams)
        {
            HttpStatusCode hCode;
            NotesViewModel mv = new NotesViewModel();
            List<AddedParam> param = new List<AddedParam>();

            if (pageindex.HasValue)
            {
                param.Add(new AddedParam { Key = "PageIndex", Value = pageindex.Value });
            }
            if (pagesize.HasValue)
            {
                param.Add(new AddedParam { Key = "PageSize", Value = pagesize.Value });
            }
            if (searchparams != null && searchparams.Count > 0)
            {
                foreach (var sparam in searchparams)
                {
                    AddedParam aparam = new AddedParam();
                    aparam.Key = sparam.Key;
                    aparam.Value = sparam.Value;
                    param.Add(aparam);
                }
            }
           ListDTOModel<NoteDTO> rList = _noteService.GetPage(param, out hCode);
           mv.PageIndex = pageindex;
           mv.PageSize = pagesize;
           mv.TotalCount = rList.TotalCount;
           mv.Notes = rList.Source;
            if (hCode != HttpStatusCode.OK)
            {
                mv.Result = Base.ViewModel.ResultType.Unsuccess;
                return Json(mv);
            }
            mv.Result = Base.ViewModel.ResultType.Success;
            return Json(mv);
        }
        [AllowAnonymous]
        [HttpPost]
        public JsonResult GetGUIDString()
        {
            GUIDGenerateViewModel mv = new GUIDGenerateViewModel();
            mv.Result = Base.ViewModel.ResultType.Success;
            return Json(mv);
        }
        [AllowAnonymous]
        [HttpPost]
        public JsonResult Save(NoteDTO obj)
        {
            HttpStatusCode hCode;
            NoteViewModel mv = new NoteViewModel();
                mv.NoteID = obj.NoteID;
              if (obj.NoteID == 0)
             {
                mv.Note = obj;
                mv.Note.CreatedBy = SessionUtils.CurrentUser.UserInstanceID;
                mv.Note = _noteService.Create(mv.Note, out hCode);
                if (hCode != HttpStatusCode.Created)
                {
                    mv.Result = Base.ViewModel.ResultType.Unsuccess;
                    return Json(mv);
                }
            }
            else
            {
                mv.Note = obj;
                List<AddedParam> param = new List<AddedParam>();
                param.Add(new AddedParam { Key = "NoteID", Value = obj.NoteID });
                param.Add(new AddedParam { Key = "MapID", Value = obj.MapID });
                param.Add(new AddedParam { Key = "Body", Value = obj.Body });
                param.Add(new AddedParam { Key = "RID", Value = obj.RID });
                param.Add(new AddedParam { Key = "Url", Value = obj.Url });
                param.Add(new AddedParam { Key = "Type", Value = obj.Type });
                mv.Note = _noteService.Update(param, out hCode);
                if (hCode != HttpStatusCode.OK)
                {
                    mv.Result = Base.ViewModel.ResultType.Unsuccess;
                    return Json(mv);
                }
            }
            mv.Result = Base.ViewModel.ResultType.Success;
            return Json(mv);
        }
        [AllowAnonymous]
        [HttpPost]
        public JsonResult Remove(int id)
        {
            HttpStatusCode hCode;
            NoteViewModel mv = new NoteViewModel();
            mv.NoteID = id;
            _noteService.Delete(id, out hCode);
            if (hCode != HttpStatusCode.OK)
            {
                mv.Result = Base.ViewModel.ResultType.Unsuccess;
                return Json(mv);
            }
            mv.Result = Base.ViewModel.ResultType.Success;
            return Json(mv);
        }
        [AllowAnonymous]
        [HttpPost]
        public JsonResult SaveList(List<NoteDTO> obj)
        {
            HttpStatusCode hCode;
            NotesViewModel mv = new NotesViewModel();
            if (obj == null || obj.Count == 0)
            {
                mv.Result = Base.ViewModel.ResultType.Success;
                return Json(mv);
            }
            try
            {
                foreach (var item in obj)
                {
                    item.CreatedBy = SessionUtils.CurrentUser.UserInstanceID;
                }
                mv.Notes = _noteService.Update(obj,out hCode);
            }
            catch
            {
                mv.Result = Base.ViewModel.ResultType.Unsuccess;
                return Json(mv);
            }
            mv.Result = Base.ViewModel.ResultType.Success;
            return Json(mv);
        }

        [AllowAnonymous]
        [HttpPost]
        public JsonResult Command(CommandDTO obj)
        {
            HttpStatusCode hCode;
            NotesViewModel mv = new NotesViewModel();
            if (obj == null)
            {
                mv.Result = Base.ViewModel.ResultType.Success;
                return Json(mv);
            }
            try
            {
                 _noteService.Command(obj, out hCode);
            }
            catch (Exception ex)
            {
                mv.Result = Base.ViewModel.ResultType.Unsuccess;
                return Json(mv);
            }
            mv.Result = Base.ViewModel.ResultType.Success;
            return Json(mv);
        }
        #endregion
    }
}

Implementation/branches/MemeMVC/MemeMVC/Views/Note/Admin.cshtml
@{
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}
@section styleContent{
}
<div class="row">
    <div class="col-md-12">
        @Html.Partial("_ArrPageNote")
    </div>
</div>
@section popup{
}
@section scripts{
    @Html.Partial("_AdminJScript")
}

Implementation/branches/MemeMVC/MemeMVC/Views/Note/Create.cshtml
@{
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}
@section styleContent{
}
<div class="row">
    <div class="col-md-12" data-bind="with:$root.NoteVM">
        <div class="row" data-bind="visible:Processing().GetProcessing('Note')()" >
           <div class="col-md-6 col-md-offset-6" style="position:absolute">
               <img src="~/Images/kloading.gif" alt="Loading ..." />
           </div>
        </div>
        <form id="formNote" class="form-horizontal" role="form" data-bind="with:Note">
             <div class="row titleholder">
                <div class="col-md-6">
                      <div class="moduletitle">
                          <span>@MemeMVC.Resource.Note.Admin.Title_Create</span>
                      </div>
                </div>
                <div class="pull-right" data-bind="visible:$root.Processing().Completed()==100">
                    <!-- ko if: IsEdit() === false -->
                     <button class="btn btn-sm" data-bind="visible:AllowEdit, click:$parent.startEditNote"><i class="glyphicon glyphicon-pencil" ></i> @MemeMVC.Resource.Note.Admin.Button_Detail_Edit</button>
                     <button class="btn btn-sm" data-bind="visible:AllowRemove, click:$parent.removeNote" ><i class="glyphicon glyphicon-trash" ></i> @MemeMVC.Resource.Note.Admin.Button_Detail_Remove</button>
                    <!-- /ko -->
                    <!-- ko if: IsEdit() === true -->
                    <button class="btn btn-sm" data-bind="click:$parent.finishEditNote" ><i class="glyphicon glyphicon-ok" ></i> @MemeMVC.Resource.Note.Admin.Button_Detail_Save</button>
                    <button class="btn btn-sm" data-bind="click:$parent.cancelEditNote" ><i class="glyphicon glyphicon-remove"></i> @MemeMVC.Resource.Note.Admin.Button_Detail_Cancel</button>
                    <!-- /ko -->
                    <button class="btn btn-sm" data-bind="click: $parent.goBackToHome"><i class="glyphicon glyphicon-arrow-left"></i>@MemeMVC.Resource.Note.Admin.Button_Detail_Back</button>
                </div>
             </div>
             @Html.Partial("_FormNote")
             <div class="row titleholder">
                <div class="col-md-6">
                </div>
                <div class="pull-right" data-bind="visible:$root.Processing().Completed()==100">
                    <!-- ko if: IsEdit() === false -->
                     <button class="btn btn-sm" data-bind="visible:AllowEdit, click:$parent.startEditNote"><i class="glyphicon glyphicon-pencil" ></i> @MemeMVC.Resource.Note.Admin.Button_Detail_Edit</button>
                     <button class="btn btn-sm" data-bind="visible:AllowRemove, click:$parent.removeNote" ><i class="glyphicon glyphicon-trash" ></i> @MemeMVC.Resource.Note.Admin.Button_Detail_Remove</button>
                    <!-- /ko -->
                    <!-- ko if: IsEdit() === true -->
                    <button class="btn btn-sm" data-bind="click:$parent.finishEditNote" ><i class="glyphicon glyphicon-ok" ></i> @MemeMVC.Resource.Note.Admin.Button_Detail_Save</button>
                    <button class="btn btn-sm" data-bind="click:$parent.cancelEditNote" ><i class="glyphicon glyphicon-remove"></i> @MemeMVC.Resource.Note.Admin.Button_Detail_Cancel</button>
                    <!-- /ko -->
                    <button class="btn btn-sm" data-bind="click: $parent.goBackToHome"><i class="glyphicon glyphicon-arrow-left"></i>@MemeMVC.Resource.Note.Admin.Button_Detail_Back</button>
                </div>
             </div>
         </form>
    </div>
</div>
@section popup{
}
@section scripts{
    @Html.Partial("_CreateJScript")
}

Implementation/branches/MemeMVC/MemeMVC/Views/Note/Detail.cshtml
@{
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}
@section styleContent{
}
<div class="row">
    <div class="col-md-12" data-bind="with:$root.NoteVM">
        <div class="row" data-bind="visible:Processing().GetProcessing('Note')()" >
           <div class="col-md-6 col-md-offset-6" style="position:absolute">
               <img src="~/Images/kloading.gif" alt="Loading ..." />
           </div>
        </div>
        <form id="formNote" class="form-horizontal" role="form" data-bind="with:Note">
                @Html.Partial("_FormNote")
           </form>
    </div>
</div>
@section popup{
}
@section scripts{
    @Html.Partial("_EditJScript")
}

Implementation/branches/MemeMVC/MemeMVC/Views/Note/Edit.cshtml
@{
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}
@section styleContent{
}
<div class="row">
    <div class="col-md-12" data-bind="with:$root.NoteVM">
        <div class="row" data-bind="visible:Processing().GetProcessing('Note')()" >
           <div class="col-md-6 col-md-offset-6" style="position:absolute">
               <img src="~/Images/kloading.gif" alt="Loading ..." />
           </div>
        </div>
        <form id="formNote" class="form-horizontal" role="form" data-bind="with:Note">
             <div class="row titleholder">
                <div class="col-md-6">
                      <div class="moduletitle">
                          <span>@MemeMVC.Resource.Note.Admin.Title_Edit</span>
                      </div>
                </div>
                <div class="pull-right" data-bind="visible:$root.Processing().Completed()==100">
                    <!-- ko if: IsEdit() === false -->
                     <button class="btn btn-sm" data-bind="visible:AllowEdit, click:$parent.startEditNote"><i class="glyphicon glyphicon-pencil" ></i> @MemeMVC.Resource.Note.Admin.Button_Detail_Edit</button>
                     <button class="btn btn-sm" data-bind="visible:AllowRemove, click:$parent.removeNote" ><i class="glyphicon glyphicon-trash" ></i> @MemeMVC.Resource.Note.Admin.Button_Detail_Remove</button>
                    <!-- /ko -->
                    <!-- ko if: IsEdit() === true -->
                    <button class="btn btn-sm" data-bind="click:$parent.finishEditNote" ><i class="glyphicon glyphicon-ok" ></i> @MemeMVC.Resource.Note.Admin.Button_Detail_Save</button>
                    <button class="btn btn-sm" data-bind="click:$parent.cancelEditNote" ><i class="glyphicon glyphicon-remove"></i> @MemeMVC.Resource.Note.Admin.Button_Detail_Cancel</button>
                    <!-- /ko -->
                    <button class="btn btn-sm" data-bind="click: $parent.goBackToHome"><i class="glyphicon glyphicon-arrow-left"></i>@MemeMVC.Resource.Note.Admin.Button_Detail_Back</button>
                </div>
             </div>
             @Html.Partial("_FormNote")
             <div class="row titleholder">
                <div class="col-md-6">
                </div>
                <div class="pull-right" data-bind="visible:$root.Processing().Completed()==100">
                    <!-- ko if: IsEdit() === false -->
                     <button class="btn btn-sm" data-bind="visible:AllowEdit, click:$parent.startEditNote"><i class="glyphicon glyphicon-pencil" ></i> @MemeMVC.Resource.Note.Admin.Button_Detail_Edit</button>
                     <button class="btn btn-sm" data-bind="visible:AllowRemove, click:$parent.removeNote" ><i class="glyphicon glyphicon-trash" ></i> @MemeMVC.Resource.Note.Admin.Button_Detail_Remove</button>
                    <!-- /ko -->
                    <!-- ko if: IsEdit() === true -->
                    <button class="btn btn-sm" data-bind="click:$parent.finishEditNote" ><i class="glyphicon glyphicon-ok" ></i> @MemeMVC.Resource.Note.Admin.Button_Detail_Save</button>
                    <button class="btn btn-sm" data-bind="click:$parent.cancelEditNote" ><i class="glyphicon glyphicon-remove"></i> @MemeMVC.Resource.Note.Admin.Button_Detail_Cancel</button>
                    <!-- /ko -->
                    <button class="btn btn-sm" data-bind="click: $parent.goBackToHome"><i class="glyphicon glyphicon-arrow-left"></i>@MemeMVC.Resource.Note.Admin.Button_Detail_Back</button>
                </div>
             </div>
        </form>
    </div>
</div>
@section popup{
}
@section scripts{
    @Html.Partial("_EditJScript")
}

Implementation/branches/MemeMVC/MemeMVC/Views/Note/_AdminJScript.cshtml
@Html.Partial("_CommonScript")
@Html.Partial("~/Views/Map/_MapJScript.cshtml")
@Html.Partial("~/Views/Map/_MapViewModelsJScript.cshtml")
@Html.Partial("_NoteJScript")
@Html.Partial("_NotePageViewModelsJScript")
<script type="text/javascript">
    var AdminViewModel = function () {
        var self = this;
        self.Processing = ko.observable(new ModelProcessing());
        self.Transition = ko.observable(new ModelTransition());
        self.NotesVM = ko.observable(null);
        self.MapsVM = ko.observable(null);
        self.InitData = function () {
 
        //define view model 
            var mapsvm = new MapsViewModel();
            mapsvm.InitModel(self.Transition, self.Processing);
            self.MapsVM(mapsvm);
            self.MapsVM().InitData();
 
            var zonesvm = new NotesPageViewModel();
            zonesvm.InitModel(self.Transition,self.Processing);
            self.NotesVM(zonesvm);
 
            //set view model relation  
            self.NotesVM().SetMapsVM(self.MapsVM);
            //int main view model
            self.NotesVM().InitData();
        };
    };
    var mv = new AdminViewModel();
    mv.InitData();
    ko.applyBindings(mv);
</script>

Implementation/branches/MemeMVC/MemeMVC/Views/Note/_NotePageViewModelsJScript.cshtml
<script type="text/javascript">
    var NotesPageViewModel = function () {
        var self = this;
        self.GetUrl = {
            getNotes: "@Url.Action("GetPage", "Note")",
            saveNote: "@Url.Action("Save", "Note")",
            removeNote: "@Url.Action("Remove", "Note")",
            gotoDetail: "@Url.Action("Detail", "Note")",
            gotoEdit: "@Url.Action("Edit", "Note")",
            gotoCreae: "@Url.Action("Create", "Note")"
        };
        self.Processing = ko.observable(null);
        self.Transition = ko.observable(null);
        self.FFInit = ko.observable(null);
        self.Paging = ko.observable(new ItemPaging(1, 20, 0));
        self.SearchCode = ko.observable("");
        self.SortedField = ko.observable(null);
        self.ArrNote = ko.observableArray([]);
        self.MapsVM = ko.observable(null);
        self.ArrSearchParam = ko.observableArray([]);
        //------- Init data for view model----------------------------
        self.InitModel = function (transition, processing) {
            self.Transition = transition;
            self.Processing = processing;
        };
        self.SetMapsVM = function (mapsvm) {
            self.MapsVM = mapsvm;
        };
        self.InitData = function () {
            InitNotes();
        };
        self.SetFFInit = function (ffinit) {
            self.FFInit(ffinit);
        };
        //--------------- For Paging and Searching -----------------------------//
        self.searchNotes = function () {
            InitNotes();
        };
        self.gotoPage = function (page) {
            if (page != self.Paging().PageIndex()) {
                self.Paging().PageIndex(page);
                InitNotes();
            }
        };
        

        self.gotoNextPage = function () {
            if (self.Paging().PageIndex() < self.Paging().TotalPages()) {
                self.Paging().PageIndex(self.Paging().PageIndex() + 1);
                InitNotes();
            }
        };
        self.gotoPrevPage = function () {
            if (self.Paging().PageIndex() > 1) {
                self.Paging().PageIndex(self.Paging().PageIndex() - 1);
                InitNotes();
            }
        };
        self.gotoDetail = function (item) {
            window.location.href = self.GetUrl.gotoDetail + "/" + item.NoteID();
        };
        self.gotoCreate = function () {
            window.location.href = self.GetUrl.gotoCreate;
        };
        self.gotoEdit = function (item) {
            window.location.href = self.GetUrl.gotoEdit + "/" + item.NoteID();
        };
        //--------------- For Item -----------------------------//
        //--------------- Model Event ----------//
        self.startAddNote = function () {
            self.Processing().SetProcessing("Notes", true);
            $.post(self.GetUrl.getGUIDString, {}, FinishInitNoteGUID);
        };
        self.startEditNote = function (item) {
            item.OldValue(ko.toJS(item));
            item.IsEdit(true);
        };
        self.finishEditNote = function (item) {
            SaveNote(item);
        };
        self.cancelEditNote = function (item) {
            if (item.NoteID() == 0) {
                self.ArrNote.remove(item);
            } else {
                ResetNote(item);
                item.IsEdit(false);
            }
        }
        self.removeNote = function (item) {
            DeleteNote(item);
        };
        self.startSort = function (field) {
            if (self.SortedField() != null) {
                if (self.SortedField().Name() == field) {
                    self.SortedField().Direction(!self.SortedField().Direction());
                } else {
                    self.SortedField().Name(field);
                    self.SortedField().Direction(false);
                }
            } else {
                self.SortedField(new SortField(field, false));
            }
            self.Paging().PageIndex(1);
            InitNotes();
        };
        //--------------- Action Function ----------//
        function FinishInitNoteGUID(data) {
            if (data.Result == "@Base.ViewModel.ResultType.Success") {
                var item = new Note(
                            0,
                            0,
                            "",
                        "",
                    "",
                    ""
                        );
                item.GUID(data.GUIDString);
                item.OldValue(ko.toJS(item));
                item.IsEdit(true);
                self.ArrNote.push(item);
            }
            self.Processing().SetProcessing("Notes", false);
        }
        function InitNotes() {
            self.Processing().SetProcessing("Notes", true);
            var postParam = SetGetParam();
            var json = JSON.stringify(postParam);
            $.ajax({
                url: self.GetUrl.getNotes,
                type: "POST",
                contentType: 'application/json; charset=utf-8',
                cache: false,
                data: json,
                success: FinishInitNotes
            });
        }
        function FinishInitNotes(data) {
            if (data.Result == "@Base.ViewModel.ResultType.Success") {
                var arrItem = ko.utils.arrayMap(data.Notes, function (item) {
                    return self.ConvertDataToNote(item);
                });
                self.ArrNote.removeAll();
                self.ArrNote(arrItem);
                self.Paging().ResetPaging(data.PageIndex, data.PageSize, data.TotalCount);
            }
            //function run after init data
            if (self.FFInit() != null) self.FFInit()();
            self.Processing().SetProcessing("Notes", false);
        }
        function SaveNote(item) {
            if (ValidateNote(item)) {
                self.Processing().SetProcessing("Notes", true);
                var json = JSON.stringify(ConvertNoteToPostObject(item));
                $.ajax({
                    url: self.GetUrl.saveNote,
                    type: "POST",
                    contentType: 'application/json; charset=utf-8',
                    cache: false,
                    data: json,
                    success: FinishSaveNote
                });
            }
        }
        function FinishSaveNote(data) {
            if (data.Result == "@Base.ViewModel.ResultType.Success") {
                var item;
                if (data.NoteID > 0) {
                    item = ko.utils.arrayFirst(self.ArrNote(), function (item1) {
                        return item1.NoteID() == data.NoteID;
                    });
                } else {
                    item = ko.utils.arrayFirst(self.ArrNote(), function (item1) {
                        return item1.GUID() == data.GUID;
                    });
                }
                if (item != null) {
                    if (item.NoteID() == 0) {
                        self.Paging().ResetPaging(self.Paging().PageIndex(), self.Paging().PageSize(), self.Paging().TotalItems() + 1);
                    }
                    item.NoteID(data.Note.NoteID);
                    item.IsEdit(false);
                }
            }
            self.Processing().SetProcessing("Notes", false);
        }
        function DeleteNote(item) {
            bootbox.confirm("<b>@MemeMVC.Resource.Note.Admin.Message_ConfirmDelete</b>", function (result) {
                if (result) {
                    if (item != undefined) {
                        if (item.NoteID() == 0) {
                            self.ArrNote.remove(item);
                        }
                        self.Processing().SetProcessing("Notes", true);
                        $.post(self.GetUrl.removeNote, { id: item.NoteID() }, function (data) {
                            if (data.Result == "@Base.ViewModel.ResultType.Success") {
                                self.ArrNote.remove(function (item) { return item.NoteID() == data.NoteID; });
                                self.Paging().ResetPaging(self.Paging().PageIndex(), self.Paging().PageSize(), self.Paging().TotalItems() - 1);
                            }
                            else {
                                bootbox.alert("@MemeMVC.Resource.Note.Admin.Message_NotConnectAPI");
                            }
                            self.Processing().SetProcessing("Notes", false);
                        });
                    }
                }
            });
        }
        function ResetNote(item) {
            item.NoteID(item.OldValue().NoteID);
            item.MapID(item.OldValue().MapID);
            item.Body(item.OldValue().Body);
            item.Url(item.OldValue().Url);
            item.RID(item.OldValue().RID);
            item.Type(item.OldValue().Type);
        }
        function ConvertNoteToPostObject(item) {
            var postObject = {
                NoteID: item.NoteID(),
                MapID: item.MapID(),
                Url: item.Url(),
                Body: item.BodyStr,
                RID: item.RID(),
                Type: item.Type()
            };
            return postObject;
        }
        self.ConvertDataToNote = function (dataItem) {
            var item = new Note(
                                         dataItem.NoteID,
                                         dataItem.MapID,
                                         dataItem.Body,
                                         dataItem.RID,
                                         dataItem.Url,
                                         dataItem.Type
                                         );
            return item;
        };
        function SetGetParam() {
            var postParam = {
                pageindex: self.Paging().PageIndex(),
                pagesize: self.Paging().PageSize(),
                searchparams: null
            };
            if (self.SortedField() != null) {
                var sparam = ko.utils.arrayFirst(self.ArrSearchParam(), function (param) { return param.Key() == "SortedField" });
                if (sparam != null) {
                    sparam.Value(self.SortedField().Name());
                    var sparam1 = ko.utils.arrayFirst(self.ArrSearchParam(), function (param) { return param.Key() == "SortedDirection" });
                    sparam1.Value(self.SortedField().Direction());
                } else {
                    self.ArrSearchParam.push(new SearchParam("SortedField", self.SortedField().Name()));
                    self.ArrSearchParam.push(new SearchParam("SortedDirection", self.SortedField().Direction()));
                }
            }
            if (self.ArrSearchParam().length > 0) {
                postParam.searchparams = ko.toJS(self.ArrSearchParam());
            }
            return postParam;
        }
        function ValidateNote(item) {
            if (item.MapID() != null) {
                if (self.MapsVM() != null) {
                    var map = ko.utils.arrayFirst(self.MapsVM().ArrMap(), function (map1) {
                        return map1.MapID() == item.MapID();
                    });
                }
            }
            else {
               
            }
            return true;
        }
        //--------------- End Action Function ----------//
        //--------------- End For item -----------------------------//
        self.GetSearchParam = function (key) {
            var param = ko.utils.arrayFirst(self.ArrSearchParam(), function (param1) { return param1.Key() == key; });
            if (param == null) {
                param = new SearchParam(key, null);
                self.ArrSearchParam.push(param);
            }
            return param;
        };
        self.SetSearchParam = function (key, value) {
            var param = ko.utils.arrayFirst(self.ArrSearchParam(), function (param1) { return param1.Key() == key; });
            if (param == null) {
                param = new SearchParam(key, value);
                self.ArrSearchParam.push(param);
            } else { param.Value(value); }
        };
    };
</script>