Implementation/branches/MemeMVC/MemeMVC/Controllers/MemeMVC/EmailTemplateController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using Ninject;
using Base;
using Base.Model.DTO;
using Base.ViewModel;
using MemeMVC.Model.DTO;
using MemeMVC.Service;
using MemeMVC.ViewModel;
namespace MemeMVC.Controllers
{
    public class EmailTemplateController : BaseController
    {
        IEmailTemplateService _emailtemplateService;
        public EmailTemplateController()
        {
        }
        [Inject]
        public EmailTemplateController(IEmailTemplateService emailtemplateService)
        {
            _emailtemplateService = emailtemplateService;
        }
        #region Normal Action
        public ActionResult Admin()
        {
            return View();
        }
        #endregion
        public ActionResult Detail(int id)
        {
            ViewBag.EmailTemplateID = id;
            return View();
        }
        public ActionResult Edit(int id)
        {
            ViewBag.EmailTemplateID = id;
            return View();
        }
        public ActionResult Create()
        {
            return View();
        }
        #region Ajax Action
        [AllowAnonymous]
        [HttpPost]
        public JsonResult Get(int? id)
        {
            HttpStatusCode hCode;
            EmailTemplateViewModel mv = new EmailTemplateViewModel();
            if (id == null || id == 0)
            {
                mv.Result = Base.ViewModel.ResultType.Success;
                mv.EmailTemplate = new EmailTemplateDTO();
                return Json(mv);
            }
            else
            {
                mv.EmailTemplate = _emailtemplateService.Get(id.Value, out hCode);
                if (hCode != HttpStatusCode.OK)
                {
                    mv.Result = Base.ViewModel.ResultType.Unsuccess;
                }
            }
            mv.Result = Base.ViewModel.ResultType.Success;
            return Json(mv);
        }
        [AllowAnonymous]
        [HttpPost]
        public JsonResult Gets(List<SearchParam> searchparams)
        {
            HttpStatusCode hCode;
            EmailTemplatesViewModel mv = new EmailTemplatesViewModel();
            List<AddedParam> param = new List<AddedParam>();
            if (searchparams != null && searchparams.Count > 0)
            {
                foreach (var sparam in searchparams)
                {
                    AddedParam aparam = new AddedParam();
                    aparam.Key = sparam.Key;
                    aparam.Value = sparam.Value;
                    param.Add(aparam);
                }
            }
            mv.EmailTemplates = _emailtemplateService.GetMany(param, out hCode).ToList();
            if (hCode != HttpStatusCode.OK)
            {
                mv.Result = Base.ViewModel.ResultType.Unsuccess;
                return Json(mv);
            }
            foreach (var item in mv.EmailTemplates) {
                item.GUID = Guid.NewGuid().ToString();
            }
            mv.Result = Base.ViewModel.ResultType.Success;
            return Json(mv);
        }
        [AllowAnonymous]
        [HttpPost]
        public JsonResult GetPage(int? pageindex,int? pagesize,List<SearchParam> searchparams)
        {
            HttpStatusCode hCode;
            EmailTemplatesViewModel mv = new EmailTemplatesViewModel();
            List<AddedParam> param = new List<AddedParam>();
            if (pageindex.HasValue)
            {
                param.Add(new AddedParam { Key = "PageIndex", Value = pageindex.Value });
            }
            if (pagesize.HasValue)
            {
                param.Add(new AddedParam { Key = "PageSize", Value = pagesize.Value });
            }
            if (searchparams != null && searchparams.Count > 0)
            {
                foreach (var sparam in searchparams)
                {
                    AddedParam aparam = new AddedParam();
                    aparam.Key = sparam.Key;
                    aparam.Value = sparam.Value;
                    param.Add(aparam);
                }
            }
           ListDTOModel<EmailTemplateDTO> rList = _emailtemplateService.GetPage(param, out hCode);
           mv.PageIndex = pageindex;
           mv.PageSize = pagesize;
           mv.TotalCount = rList.TotalCount;
           mv.EmailTemplates = rList.Source;
            if (hCode != HttpStatusCode.OK)
            {
                mv.Result = Base.ViewModel.ResultType.Unsuccess;
                return Json(mv);
            }
            mv.Result = Base.ViewModel.ResultType.Success;
            return Json(mv);
        }
        [AllowAnonymous]
        [HttpPost]
        public JsonResult GetGUIDString()
        {
            GUIDGenerateViewModel mv = new GUIDGenerateViewModel();
            mv.Result = Base.ViewModel.ResultType.Success;
            return Json(mv);
        }
        [AllowAnonymous]
        [HttpPost]
        public JsonResult Save(EmailTemplateDTO obj)
        {
            HttpStatusCode hCode;
            EmailTemplateViewModel mv = new EmailTemplateViewModel();
                mv.EmailTemplateID = obj.EmailTemplateID;
              if (obj.EmailTemplateID == 0)
             {
                mv.GUID = obj.GUID;
                mv.EmailTemplate = obj;
                mv.EmailTemplate.CreatedBy = SessionUtils.CurrentUser.UserInstanceID;
                mv.EmailTemplate = _emailtemplateService.Create(mv.EmailTemplate, out hCode);
                if (hCode != HttpStatusCode.Created)
                {
                    mv.Result = Base.ViewModel.ResultType.Unsuccess;
                    return Json(mv);
                }
            }
            else
            {
                mv.EmailTemplate = obj;
                List<AddedParam> param = new List<AddedParam>();
                param.Add(new AddedParam { Key = "EmailTemplateID", Value = obj.EmailTemplateID });
                param.Add(new AddedParam { Key = "EmailTemplateName", Value = obj.EmailTemplateName });
                param.Add(new AddedParam { Key = "Subject", Value = obj.Subject });
                param.Add(new AddedParam { Key = "EmailTemplateContent", Value = obj.EmailTemplateContent });
                mv.EmailTemplate = _emailtemplateService.Update(param, out hCode);
                if (hCode != HttpStatusCode.OK)
                {
                    mv.Result = Base.ViewModel.ResultType.Unsuccess;
                    return Json(mv);
                }
            }
            mv.Result = Base.ViewModel.ResultType.Success;
            return Json(mv);
        }
        [AllowAnonymous]
        [HttpPost]
        public JsonResult Remove(int id)
        {
            HttpStatusCode hCode;
            EmailTemplateViewModel mv = new EmailTemplateViewModel();
            mv.EmailTemplateID = id;
            _emailtemplateService.Delete(id, out hCode);
            if (hCode != HttpStatusCode.OK)
            {
                mv.Result = Base.ViewModel.ResultType.Unsuccess;
                return Json(mv);
            }
            mv.Result = Base.ViewModel.ResultType.Success;
            return Json(mv);
        }
        [AllowAnonymous]
        [HttpPost]
        public JsonResult SaveList(List<EmailTemplateDTO> obj)
        {
            HttpStatusCode hCode;
            EmailTemplatesViewModel mv = new EmailTemplatesViewModel();
            if (obj == null || obj.Count == 0)
            {
                mv.Result = Base.ViewModel.ResultType.Success;
                return Json(mv);
            }
            try
            {
                foreach (var item in obj)
                {
                    item.CreatedBy = SessionUtils.CurrentUser.UserInstanceID;
                }
                mv.EmailTemplates = _emailtemplateService.Update(obj,out hCode);
            }
            catch
            {
                mv.Result = Base.ViewModel.ResultType.Unsuccess;
                return Json(mv);
            }
            mv.Result = Base.ViewModel.ResultType.Success;
            return Json(mv);
        }
        #endregion
    }
}

Implementation/branches/MemeMVC/MemeMVC/Views/EmailTemplate/Admin.cshtml
@{
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}
@section styleContent{
}
<div class="row">
    <div class="col-md-12">
        @Html.Partial("_ArrPageEmailTemplate")
    </div>
</div>
@section popup{
}
@section scripts{
    @Html.Partial("_AdminJScript")
}

Implementation/branches/MemeMVC/MemeMVC/Views/EmailTemplate/Create.cshtml
@{
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}
@section styleContent{
}
<div class="row">
    <div class="col-md-12" data-bind="with:$root.EmailTemplateVM">
        <div class="row" data-bind="visible:Processing().GetProcessing('EmailTemplate')()" >
           <div class="col-md-6 col-md-offset-6" style="position:absolute">
               <img src="~/Images/kloading.gif" alt="Loading ..." />
           </div>
        </div>
        <form id="formEmailTemplate" class="form-horizontal" role="form" data-bind="with:EmailTemplate">
             <div class="row titleholder">
                <div class="col-md-6">
                      <div class="moduletitle">
                          <span>@MemeMVC.Resource.EmailTemplate.Admin.Title_Create</span>
                      </div>
                </div>
                <div class="pull-right" data-bind="visible:$root.Processing().Completed()==100">
                    <!-- ko if: IsEdit() === false -->
                     <button class="btn btn-sm" data-bind="visible:AllowEdit, click:$parent.startEditEmailTemplate"><i class="glyphicon glyphicon-pencil" ></i> @MemeMVC.Resource.EmailTemplate.Admin.Button_Detail_Edit</button>
                     <button class="btn btn-sm" data-bind="visible:AllowRemove, click:$parent.removeEmailTemplate" ><i class="glyphicon glyphicon-trash" ></i> @MemeMVC.Resource.EmailTemplate.Admin.Button_Detail_Remove</button>
                    <!-- /ko -->
                    <!-- ko if: IsEdit() === true -->
                    <button class="btn btn-sm" data-bind="click:$parent.finishEditEmailTemplate" ><i class="glyphicon glyphicon-ok" ></i> @MemeMVC.Resource.EmailTemplate.Admin.Button_Detail_Save</button>
                    <button class="btn btn-sm" data-bind="click:$parent.cancelEditEmailTemplate" ><i class="glyphicon glyphicon-remove"></i> @MemeMVC.Resource.EmailTemplate.Admin.Button_Detail_Cancel</button>
                    <!-- /ko -->
                    <button class="btn btn-sm" data-bind="click: $parent.goBackToHome"><i class="glyphicon glyphicon-arrow-left"></i>@MemeMVC.Resource.EmailTemplate.Admin.Button_Detail_Back</button>
                </div>
             </div>
             @Html.Partial("_FormEmailTemplate")
             <div class="row titleholder">
                <div class="col-md-6">
                </div>
                <div class="pull-right" data-bind="visible:$root.Processing().Completed()==100">
                    <!-- ko if: IsEdit() === false -->
                     <button class="btn btn-sm" data-bind="visible:AllowEdit, click:$parent.startEditEmailTemplate"><i class="glyphicon glyphicon-pencil" ></i> @MemeMVC.Resource.EmailTemplate.Admin.Button_Detail_Edit</button>
                     <button class="btn btn-sm" data-bind="visible:AllowRemove, click:$parent.removeEmailTemplate" ><i class="glyphicon glyphicon-trash" ></i> @MemeMVC.Resource.EmailTemplate.Admin.Button_Detail_Remove</button>
                    <!-- /ko -->
                    <!-- ko if: IsEdit() === true -->
                    <button class="btn btn-sm" data-bind="click:$parent.finishEditEmailTemplate" ><i class="glyphicon glyphicon-ok" ></i> @MemeMVC.Resource.EmailTemplate.Admin.Button_Detail_Save</button>
                    <button class="btn btn-sm" data-bind="click:$parent.cancelEditEmailTemplate" ><i class="glyphicon glyphicon-remove"></i> @MemeMVC.Resource.EmailTemplate.Admin.Button_Detail_Cancel</button>
                    <!-- /ko -->
                    <button class="btn btn-sm" data-bind="click: $parent.goBackToHome"><i class="glyphicon glyphicon-arrow-left"></i>@MemeMVC.Resource.EmailTemplate.Admin.Button_Detail_Back</button>
                </div>
             </div>
         </form>
    </div>
</div>
@section popup{
}
@section scripts{
    @Html.Partial("_CreateJScript")
}

Implementation/branches/MemeMVC/MemeMVC/Views/EmailTemplate/Detail.cshtml
@{
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}
@section styleContent{
}
<div class="row">
    <div class="col-md-12" data-bind="with:$root.EmailTemplateVM">
        <div class="row" data-bind="visible:Processing().GetProcessing('EmailTemplate')()" >
           <div class="col-md-6 col-md-offset-6" style="position:absolute">
               <img src="~/Images/kloading.gif" alt="Loading ..." />
           </div>
        </div>
        <form id="formEmailTemplate" class="form-horizontal" role="form" data-bind="with:EmailTemplate">
                @Html.Partial("_FormEmailTemplate")
           </form>
    </div>
</div>
@section popup{
}
@section scripts{
    @Html.Partial("_EditJScript")
}

Implementation/branches/MemeMVC/MemeMVC/Views/EmailTemplate/Edit.cshtml
@{
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}
@section styleContent{
}
<div class="row">
    <div class="col-md-12" data-bind="with:$root.EmailTemplateVM">
        <div class="row" data-bind="visible:Processing().GetProcessing('EmailTemplate')()" >
           <div class="col-md-6 col-md-offset-6" style="position:absolute">
               <img src="~/Images/kloading.gif" alt="Loading ..." />
           </div>
        </div>
        <form id="formEmailTemplate" class="form-horizontal" role="form" data-bind="with:EmailTemplate">
             <div class="row titleholder">
                <div class="col-md-6">
                      <div class="moduletitle">
                          <span>@MemeMVC.Resource.EmailTemplate.Admin.Title_Edit</span>
                      </div>
                </div>
                <div class="pull-right" data-bind="visible:$root.Processing().Completed()==100">
                    <!-- ko if: IsEdit() === false -->
                     <button class="btn btn-sm" data-bind="visible:AllowEdit, click:$parent.startEditEmailTemplate"><i class="glyphicon glyphicon-pencil" ></i> @MemeMVC.Resource.EmailTemplate.Admin.Button_Detail_Edit</button>
                     <button class="btn btn-sm" data-bind="visible:AllowRemove, click:$parent.removeEmailTemplate" ><i class="glyphicon glyphicon-trash" ></i> @MemeMVC.Resource.EmailTemplate.Admin.Button_Detail_Remove</button>
                    <!-- /ko -->
                    <!-- ko if: IsEdit() === true -->
                    <button class="btn btn-sm" data-bind="click:$parent.finishEditEmailTemplate" ><i class="glyphicon glyphicon-ok" ></i> @MemeMVC.Resource.EmailTemplate.Admin.Button_Detail_Save</button>
                    <button class="btn btn-sm" data-bind="click:$parent.cancelEditEmailTemplate" ><i class="glyphicon glyphicon-remove"></i> @MemeMVC.Resource.EmailTemplate.Admin.Button_Detail_Cancel</button>
                    <!-- /ko -->
                    <button class="btn btn-sm" data-bind="click: $parent.goBackToHome"><i class="glyphicon glyphicon-arrow-left"></i>@MemeMVC.Resource.EmailTemplate.Admin.Button_Detail_Back</button>
                </div>
             </div>
             @Html.Partial("_FormEmailTemplate")
             <div class="row titleholder">
                <div class="col-md-6">
                </div>
                <div class="pull-right" data-bind="visible:$root.Processing().Completed()==100">
                    <!-- ko if: IsEdit() === false -->
                     <button class="btn btn-sm" data-bind="visible:AllowEdit, click:$parent.startEditEmailTemplate"><i class="glyphicon glyphicon-pencil" ></i> @MemeMVC.Resource.EmailTemplate.Admin.Button_Detail_Edit</button>
                     <button class="btn btn-sm" data-bind="visible:AllowRemove, click:$parent.removeEmailTemplate" ><i class="glyphicon glyphicon-trash" ></i> @MemeMVC.Resource.EmailTemplate.Admin.Button_Detail_Remove</button>
                    <!-- /ko -->
                    <!-- ko if: IsEdit() === true -->
                    <button class="btn btn-sm" data-bind="click:$parent.finishEditEmailTemplate" ><i class="glyphicon glyphicon-ok" ></i> @MemeMVC.Resource.EmailTemplate.Admin.Button_Detail_Save</button>
                    <button class="btn btn-sm" data-bind="click:$parent.cancelEditEmailTemplate" ><i class="glyphicon glyphicon-remove"></i> @MemeMVC.Resource.EmailTemplate.Admin.Button_Detail_Cancel</button>
                    <!-- /ko -->
                    <button class="btn btn-sm" data-bind="click: $parent.goBackToHome"><i class="glyphicon glyphicon-arrow-left"></i>@MemeMVC.Resource.EmailTemplate.Admin.Button_Detail_Back</button>
                </div>
             </div>
        </form>
    </div>
</div>
@section popup{
}
@section scripts{
    @Html.Partial("_EditJScript")
}

Implementation/branches/MemeMVC/MemeMVC/Views/EmailTemplate/_AdminJScript.cshtml
@Html.Partial("_CommonScript")
@Html.Partial("_ValidateJScript")
@Html.Partial("_FormatJScript")
@Html.Partial("_EmailTemplateJScript")
@Html.Partial("_EmailTemplatePageViewModelsJScript")
<script type="text/javascript">
    var AdminViewModel = function () {
        var self = this;
        self.Processing = ko.observable(new ModelProcessing());
        self.Transition = ko.observable(new ModelTransition());
        self.EmailTemplatesVM = ko.observable(null);
        self.InitData = function () {
 
        //define view model 
 
            var emailtemplatesvm = new EmailTemplatesPageViewModel();
            emailtemplatesvm.InitModel(self.Transition,self.Processing);
            self.EmailTemplatesVM(emailtemplatesvm);
 
            //set view model relation  
            //int main view model
            self.EmailTemplatesVM().InitData();
        };
    };
    var mv = new AdminViewModel();
    mv.InitData();
    ko.applyBindings(mv);
</script>

Implementation/branches/MemeMVC/MemeMVC/Views/EmailTemplate/_ArrPageEmailTemplate.cshtml
<div class="row" data-bind="with:EmailTemplatesVM">
    <div class="col-md-12">
        <div class="row">
            <div class="col-md-12">
                <div class="dark">
                    <div class="row">
                        <div class="col-md-5">
                            <span>@MemeMVC.Resource.EmailTemplate.Admin.Title </span>
                        </div>
                        <div class="col-md-3">
                            <div class="input-group">
                                <input type="text" class="form-control" placeholder="@MemeMVC.Resource.EmailTemplate.Admin.PlaceHolder_Search" data-bind="value:GetSearchParam('SearchCode')().Value" />
                                <div class="input-group-btn">
                                    <button class="btn btn-default" type="button" data-bind="click:searchEmailTemplates" style="margin-top:4px;">
                                        <i class="glyphicon glyphicon-search"></i>@MemeMVC.Resource.EmailTemplate.Admin.Button_Search
                                    </button>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-4">
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div data-bind="visible:Processing().GetProcessing('EmailTemplates')" class="row" style="position: absolute">
            <div class="col-md-5 col-md-offset-5">
                <img src="~/Images/kloading.gif" alt="Loading..." />
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                @Html.Partial("_TableEmailTemplate")
            </div>
        </div>
    </div>
</div>

Implementation/branches/MemeMVC/MemeMVC/Views/EmailTemplate/_CreateJScript.cshtml
@Html.Partial("_CommonScript")
@Html.Partial("_EmailTemplateJScript")
@Html.Partial("_EmailTemplateViewModelJScript")
<script type="text/javascript">
    var CreateViewModel = function () {
        var self = this;
        self.Processing = ko.observable(new ModelProcessing());
        self.Transition = ko.observable(new ModelTransition());
        self.EmailTemplateVM = ko.observable(null);
        self.InitData = function () {
 
        //define view model 
 
            var emailtemplatevm = new EmailTemplateViewModel();
            emailtemplatevm.InitModel(self.Transition,self.Processing);
            self.EmailTemplateVM(emailtemplatevm);
 
            //set view model relation  
            //int main view model
            self.EmailTemplateVM().InitData();
        };
    };
    var mv = new CreateViewModel();
    mv.InitData();
    ko.applyBindings(mv);
</script>

Implementation/branches/MemeMVC/MemeMVC/Views/EmailTemplate/_DetailJScript.cshtml
@Html.Partial("_CommonScript")
@Html.Partial("_EmailTemplateJScript")
@Html.Partial("_EmailTemplateViewModelJScript")
<script type="text/javascript">
    var DetailViewModel = function () {
        var self = this;
        self.Processing = ko.observable(new ModelProcessing());
        self.Transition = ko.observable(new ModelTransition());
        self.EmailTemplateVM = ko.observable(null);
        self.InitData = function () {
 
        //define view model 
 
            var emailtemplatevm = new EmailTemplateViewModel();
            emailtemplatevm.InitModel(self.Transition,self.Processing);
            self.EmailTemplateVM(emailtemplatevm);
 
            //int main view model
            var id = parseInt("@ViewBag.EmailTemplateID");
            self.EmailTemplateVM().SetEmailTemplateID(id);
            self.EmailTemplateVM().InitData();
        };
    };
    var mv = new DetailViewModel();
    mv.InitData();
    ko.applyBindings(mv);
</script>

Implementation/branches/MemeMVC/MemeMVC/Views/EmailTemplate/_EditJScript.cshtml
@Html.Partial("_CommonScript")
@Html.Partial("_EmailTemplateJScript")
@Html.Partial("_EmailTemplateViewModelJScript")
<script type="text/javascript">
    var EditViewModel = function () {
        var self = this;
        self.Processing = ko.observable(new ModelProcessing());
        self.Transition = ko.observable(new ModelTransition());
        self.EmailTemplateVM = ko.observable(null);
        self.InitData = function () {
 
        //define view model 
 
            var emailtemplatevm = new EmailTemplateViewModel();
            emailtemplatevm.InitModel(self.Transition,self.Processing);
            self.EmailTemplateVM(emailtemplatevm);
 
            //set view model relation  
            //int main view model
            var id = parseInt("@ViewBag.EmailTemplateID");
            self.EmailTemplateVM().SetEmailTemplateID(id);
            self.EmailTemplateVM().InitData();
        };
    };
    var mv = new EditViewModel();
    mv.InitData();
    ko.applyBindings(mv);
</script>

Implementation/branches/MemeMVC/MemeMVC/Views/EmailTemplate/_EmailTemplateViewModelJScript.cshtml
<script type="text/javascript">
var EmailTemplateViewModel = function(){
var self = this;
    self.GetUrl = {
        getEmailTemplate : "@Url.Action("Get","EmailTemplate")",
        saveEmailTemplate   : "@Url.Action("Save", "EmailTemplate")",
        removeEmailTemplate : "@Url.Action("Remove", "EmailTemplate")",
        gotoMaster       : "@Url.Action("Admin", "EmailTemplate")",
        getGUIDString : "@Url.Action("GetGUIDString","EmailTemplate")"
    };
    self.EmailTemplateID = ko.observable(null);
    self.EmailTemplate = ko.observable(null);
    self.Transition = ko.observable(null);
    self.Processing = ko.observable(null);
    self.FFInit = ko.observable(null);
    self.InitModel = function(transition,processing){
        self.Transition = transition;
        self.Processing = processing;
    };
    self.SetFFInit = function(ffinit){
        self.FFInit(ffinit);
    };
    self.SetEmailTemplateID = function(id){
        self.EmailTemplateID(id);
    }
    self.InitData =function(){
        InitEmailTemplate();
    };
            self.startEditEmailTemplate = function(emailtemplate){
                emailtemplate.OldValue(ko.toJS(emailtemplate));
                emailtemplate.IsEdit(true);
             }
             self.finishEditEmailTemplate = function(emailtemplate){
                SaveEmailTemplate(emailtemplate);
             }
             self.cancelEditEmailTemplate = function(emailtemplate){
                ResetEmailTemplate(emailtemplate);
                emailtemplate.IsEdit(false);
             }
             self.removeEmailTemplate = function(emailtemplate){
                 DeleteEmailTemplate(emailtemplate);
             };
             self.completeEmailTemplate = function(emailtemplate){
                 CompleteEmailTemplate(emailtemplate);
             };
             self.goBackToHome = function(){
                 window.location.href = self.GetUrl.gotoMaster;
             };
            function InitEmailTemplate(){
               self.Processing().SetProcessing("EmailTemplate",true);
               if(self.EmailTemplateID()>0){
                  $.post(self.GetUrl.getEmailTemplate,{id:self.EmailTemplateID()},FinishInitEmailTemplate);
               }else{
                  $.post(self.GetUrl.getGUIDString,{},FinishInitEmailTemplateGUID);
               }
            };
            function FinishInitEmailTemplate(data){
                 if(data.Result == "@Base.ViewModel.ResultType.Success"){
                    self.EmailTemplate(self.ConvertDataToEmailTemplate(data.EmailTemplate));
                 }
                 if (self.FFInit() != null) self.FFInit()();
                 self.Processing().SetProcessing("EmailTemplate",false);
            }
            function FinishInitEmailTemplateGUID(data){
                if(data.Result == "@Base.ViewModel.ResultType.Success"){
                         var newEmailTemplate = new EmailTemplate(
                                0,
                                "",
                                "",
                                ""
                            );
                        newEmailTemplate.GUID(data.GUIDString);
                        self.EmailTemplate(newEmailTemplate);
                        self.EmailTemplate().AllowEdit(true);
                        self.EmailTemplate().AllowRemove(true);
                        self.EmailTemplate().AllowSendTo(false);
                        self.EmailTemplate().AllowPrint(false);
                        self.EmailTemplate().AllowAddDetail(true);
                        self.EmailTemplate().IsEdit(true);
                  }
                self.Processing().SetProcessing("EmailTemplate",false);
            }
            function SaveEmailTemplate(emailtemplate){
                if(ValidateEmailTemplate(emailtemplate )){
                  self.Processing().SetProcessing("EmailTemplate",true);
                  $.post(self.GetUrl.saveEmailTemplate,ConvertEmailTemplateToPostObject(emailtemplate),FinishSaveEmailTemplate);
                }
             }
             function ValidateEmailTemplate(item){
                return true;
             }
             function FinishSaveEmailTemplate(data){
                 if(data.Result == "@Base.ViewModel.ResultType.Success"){
                     self.EmailTemplate().EmailTemplateID(data.EmailTemplate.EmailTemplateID);
                     self.EmailTemplateID(data.EmailTemplate.EmailTemplateID);
                     self.EmailTemplate().IsEdit(false);
                 }else{
                    bootbox.alert("@MemeMVC.Resource.EmailTemplate.Admin.Message_SaveFail");
                 }
                 self.Processing().SetProcessing("EmailTemplate",false);
             }
             function DeleteEmailTemplate(emailtemplate){
                 self.Processing().SetProcessing("EmailTemplate",true);
                 bootbox.confirm("<b>@MemeMVC.Resource.EmailTemplate.Admin.Message_ConfirmDelete</b>",
                                  function(result){
                            if(result){
                                if(emailtemplate != undefined){
                                    $.post(self.GetUrl.removeEmailTemplate,{id: self.EmailTemplate().EmailTemplateID()},
                                         function(data){
                                            self.Processing().SetProcessing("EmailTemplate",false);
                                            if(data.Result == "@Base.ViewModel.ResultType.Success"){
                                                window.location.href = self.GetUrl.gotoMaster;
                                            }else{
                                                bootbox.alert("@MemeMVC.Resource.EmailTemplate.Admin.Message_NotConnectAPI");
                                            }
                                        });
                                }
                            }
                        }
                 );
             }
            function CompleteEmailTemplate(emailtemplate){
            }
             function ConvertEmailTemplateToPostObject(emailtemplate){
                var postObject = {
                                 EmailTemplateID:emailtemplate.EmailTemplateID(),
                                 EmailTemplateName:emailtemplate.EmailTemplateName(),
                                 Subject:emailtemplate.Subject(),
                                 EmailTemplateContent:emailtemplate.EmailTemplateContent(),
                                 GUID:emailtemplate.GUID()
                                };
                return postObject;
             }
             function ResetEmailTemplate(emailtemplate){
                 emailtemplate.EmailTemplateID(emailtemplate.OldValue().EmailTemplateID);
                 emailtemplate.EmailTemplateName(emailtemplate.OldValue().EmailTemplateName);
                 emailtemplate.Subject(emailtemplate.OldValue().Subject);
                 emailtemplate.EmailTemplateContent(emailtemplate.OldValue().EmailTemplateContent);
             }
             self.ConvertDataToEmailTemplate = function(dataItem){
                    var emailtemplate = new EmailTemplate(
                                                 dataItem.EmailTemplateID,
                                                 dataItem.EmailTemplateName,
                                                 dataItem.Subject,
                                                 dataItem.EmailTemplateContent
                                                 );
                    return emailtemplate;
             }
        };
</script>