Implementation/branches/MemeMVC/MemeMVC/Controllers/MemeMVC/MapController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using Ninject;
using Base;
using Base.Model.DTO;
using Base.ViewModel;
using MemeMVC.Model.DTO;
using MemeMVC.Service;
using MemeMVC.ViewModel;
using MemeMVC.Model.DTO.Mongo;
using MemeMVC.Repository;
using Newtonsoft.Json;
using MongoDB.Bson;
namespace MemeMVC.Controllers
{
    public class MapController : BaseController
    {
        IMapService _mapService;
        ICommentRepository _commentRepository;
        IUserService _userService;
        IUserMapSharedRepository _userMapSharedRepo;
        ITaskEntityRepository _taskEntityRepo;
        ITaskPriorityRepository _taskPriorityRepo;
        ITaskStatusRepository _taskStatusRepo;
        ITaskTypeRepository _taskTypeRepo;
        public MapController()
        {
        }
        [Inject]
        public MapController(IMapService mapService, ICommentRepository commentRepository, IUserService userService, 
            IUserMapSharedRepository userMapSharedRepo, 
            ITaskEntityRepository taskEntityRepo,
            ITaskPriorityRepository taskPriorityRepo,
            ITaskStatusRepository taskStatusRepo,
            ITaskTypeRepository taskTypeRepo)
        {
            _mapService = mapService;
            _commentRepository = commentRepository;
            _userService = userService;
            _userMapSharedRepo = userMapSharedRepo;
            _taskEntityRepo = taskEntityRepo;
            _taskPriorityRepo = taskPriorityRepo;
            _taskStatusRepo = taskStatusRepo;
            _taskTypeRepo = taskTypeRepo;
        }
        #region Normal Action
        public ActionResult Admin()
        {
            return View();
        }

        public ActionResult Detail1()
        {
            string url = Request.Url.AbsolutePath;
            int projectid = Convert.ToInt32(url.Substring(url.LastIndexOf("/") + 1));
            ViewBag.ProjectID = projectid;
            return View();
        }

        #endregion
        public ActionResult Detail(int id)
        {
            ViewBag.MapID = id;
            ViewBag.UserID = SessionUtils.CurrentUser.UserID;
            ViewBag.UserName = SessionUtils.CurrentUser.UserName;
            return View();
        }
        public ActionResult DetailList(int id)
        {
            ViewBag.MapID = id;
            return View();
        }
        [AllowAnonymous]
        [HttpGet]
        public ActionResult View(int id)
        {
            ViewBag.MapID = id;
            return View();
        }
        [AllowAnonymous]
        public ActionResult ViewLinkedIn()
        {
            ViewBag.PhotoUrl = "";
            ViewBag.ProfileName = "";
            ViewBag.ProfileId = "";
            ViewBag.MapID = 0;
            if (Session["LinkedInUser"] != null)
            {
                LiPerson user= Session["LinkedInUser"] as LiPerson;
                ViewBag.PhotoUrl = user.PictureUrl;
                ViewBag.ProfileName = user.FirstName + " " + user.LastName ;
                ViewBag.ProfileId = user.id;
            }

            return View();
        }


        public ActionResult Edit(int id)
        {
            ViewBag.MapID = id;
            return View();
        }
        public ActionResult Create()
        {
            return View();
        }
        #region Ajax Action
        [AllowAnonymous]
        [HttpPost]
        public JsonResult Get(int? id)
        {
            HttpStatusCode hCode;
            MapViewModel mv = new MapViewModel();
            if (id == null || id == 0)
            {
                mv.Result = Base.ViewModel.ResultType.Success;
                mv.Map = new MapDTO();
                return Json(mv);
            }
            else
            {
                mv.Map = _mapService.Get(id.Value, out hCode);
                if (hCode != HttpStatusCode.OK)
                {
                    mv.Result = Base.ViewModel.ResultType.Unsuccess;
                }
            }
            mv.Result = Base.ViewModel.ResultType.Success;
            return Json(mv);
        }
        [AllowAnonymous]
        [HttpPost]
        public JsonResult Gets(List<SearchParam> searchparams)
        {
            HttpStatusCode hCode;
            MapsViewModel mv = new MapsViewModel();
            List<AddedParam> param = new List<AddedParam>();
            if (searchparams != null && searchparams.Count > 0)
            {
                foreach (var sparam in searchparams)
                {
                    AddedParam aparam = new AddedParam();
                    aparam.Key = sparam.Key;
                    aparam.Value = sparam.Value;
                    param.Add(aparam);
                }
            }
            mv.Maps = _mapService.GetMany(param, out hCode).ToList();
            if (hCode != HttpStatusCode.OK)
            {
                mv.Result = Base.ViewModel.ResultType.Unsuccess;
                return Json(mv);
            }
            foreach (var item in mv.Maps)
            {
                item.GUID = Guid.NewGuid().ToString();
            }
            mv.Result = Base.ViewModel.ResultType.Success;
            return Json(mv);
        }
        [AllowAnonymous]
        [HttpPost]
        public JsonResult GetPage(int? pageindex, int? pagesize, List<SearchParam> searchparams)
        {
            HttpStatusCode hCode;
            MapsViewModel mv = new MapsViewModel();
            List<AddedParam> param = new List<AddedParam>();

            if (pageindex.HasValue)
            {
                param.Add(new AddedParam { Key = "PageIndex", Value = pageindex.Value });
            }
            if (pagesize.HasValue)
            {
                param.Add(new AddedParam { Key = "PageSize", Value = pagesize.Value });
            }
            if (searchparams != null && searchparams.Count > 0)
            {
                foreach (var sparam in searchparams)
                {
                    AddedParam aparam = new AddedParam();
                    aparam.Key = sparam.Key;
                    aparam.Value = sparam.Value;
                    param.Add(aparam);
                }
            }
            ListDTOModel<MapDTO> rList = _mapService.GetPage(param, out hCode);
            mv.PageIndex = pageindex;
            mv.PageSize = pagesize;
            mv.TotalCount = rList.TotalCount;
            mv.Maps = rList.Source;
            foreach (var p in mv.Maps)
            {
                p.LastAccessDate = p.ModifiedDate.HasValue ? p.ModifiedDate.Value.ToString("dd/MM/yyyy HH:mm") : p.CreatedDate.ToString("dd/MM/yyyy HH:mm");
            }
            if (hCode != HttpStatusCode.OK)
            {
                mv.Result = Base.ViewModel.ResultType.Unsuccess;
                return Json(mv);
            }
            mv.Result = Base.ViewModel.ResultType.Success;
            return Json(mv);
        }
        [AllowAnonymous]
        [HttpPost]
        public JsonResult GetGUIDString()
        {
            GUIDGenerateViewModel mv = new GUIDGenerateViewModel();
            mv.Result = Base.ViewModel.ResultType.Success;
            return Json(mv);
        }
        [AllowAnonymous]
        [HttpPost]
        public JsonResult Save(MapDTO obj)
        {
            HttpStatusCode hCode;
            MapViewModel mv = new MapViewModel();
            mv.MapID = obj.MapID;
            if (obj.MapID == 0)
            {
                mv.GUID = obj.GUID;
                mv.Map = obj;
                mv.Map.CreatedBy = SessionUtils.CurrentUser.UserInstanceID;
                mv.Map = _mapService.Create(mv.Map, out hCode);
                if (hCode != HttpStatusCode.Created)
                {
                    mv.Result = Base.ViewModel.ResultType.Unsuccess;
                    return Json(mv);
                }
            }
            else
            {
                mv.Map = obj;
                List<AddedParam> param = new List<AddedParam>();
                param.Add(new AddedParam { Key = "MapID", Value = obj.MapID });
                param.Add(new AddedParam { Key = "ProjectID", Value = obj.ProjectID });
                param.Add(new AddedParam { Key = "Name", Value = obj.Name });
                param.Add(new AddedParam { Key = "Description", Value = obj.Description });
                mv.Map = _mapService.Update(param, out hCode);
                if (hCode != HttpStatusCode.OK)
                {
                    mv.Result = Base.ViewModel.ResultType.Unsuccess;
                    return Json(mv);
                }
            }
            mv.Result = Base.ViewModel.ResultType.Success;
            return Json(mv);
        }
        [AllowAnonymous]
        [HttpPost]
        public JsonResult Remove(int id)
        {
            HttpStatusCode hCode;
            MapViewModel mv = new MapViewModel();
            mv.MapID = id;
            _mapService.Delete(id, out hCode);
            if (hCode != HttpStatusCode.OK)
            {
                mv.Result = Base.ViewModel.ResultType.Unsuccess;
                return Json(mv);
            }
            mv.Result = Base.ViewModel.ResultType.Success;
            return Json(mv);
        }
        [AllowAnonymous]
        [HttpPost]
        public JsonResult SaveList(List<MapDTO> obj)
        {
            HttpStatusCode hCode;
            MapsViewModel mv = new MapsViewModel();
            if (obj == null || obj.Count == 0)
            {
                mv.Result = Base.ViewModel.ResultType.Success;
                return Json(mv);
            }
            try
            {
                foreach (var item in obj)
                {
                    item.CreatedBy = SessionUtils.CurrentUser.UserInstanceID;
                }
                mv.Maps = _mapService.Update(obj, out hCode);
            }
            catch
            {
                mv.Result = Base.ViewModel.ResultType.Unsuccess;
                return Json(mv);
            }

Implementation/branches/MemeMVC/MemeMVC/Views/Map/Create.cshtml
@{
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}
@section styleContent{
}
<div class="row">
    <div class="col-md-12" data-bind="with:$root.MapVM">
        <div class="row" data-bind="visible:Processing().GetProcessing('Map')()" >
           <div class="col-md-6 col-md-offset-6" style="position:absolute">
               <img src="~/Images/kloading.gif" alt="Loading ..." />
           </div>
        </div>
        <form id="formMap" class="form-horizontal" role="form" data-bind="with:Map">
             <div class="row titleholder">
                <div class="col-md-6">
                      <div class="moduletitle">
                          <span>@MemeMVC.Resource.Map.Admin.Title_Create</span>
                      </div>
                </div>
                <div class="pull-right" data-bind="visible:$root.Processing().Completed()==100">
                    <!-- ko if: IsEdit() === false -->
                     <button class="btn btn-sm" data-bind="visible:AllowEdit, click:$parent.startEditMap"><i class="glyphicon glyphicon-pencil" ></i> @MemeMVC.Resource.Map.Admin.Button_Detail_Edit</button>
                     <button class="btn btn-sm" data-bind="visible:AllowRemove, click:$parent.removeMap" ><i class="glyphicon glyphicon-trash" ></i> @MemeMVC.Resource.Map.Admin.Button_Detail_Remove</button>
                    <!-- /ko -->
                    <!-- ko if: IsEdit() === true -->
                    <button class="btn btn-sm" data-bind="click:$parent.finishEditMap" ><i class="glyphicon glyphicon-ok" ></i> @MemeMVC.Resource.Map.Admin.Button_Detail_Save</button>
                    <button class="btn btn-sm" data-bind="click:$parent.cancelEditMap" ><i class="glyphicon glyphicon-remove"></i> @MemeMVC.Resource.Map.Admin.Button_Detail_Cancel</button>
                    <!-- /ko -->
                    <button class="btn btn-sm" data-bind="click: $parent.goBackToHome"><i class="glyphicon glyphicon-arrow-left"></i>@MemeMVC.Resource.Map.Admin.Button_Detail_Back</button>
                </div>
             </div>
             @Html.Partial("_FormMap")
             <div class="row titleholder">
                <div class="col-md-6">
                </div>
                <div class="pull-right" data-bind="visible:$root.Processing().Completed()==100">
                    <!-- ko if: IsEdit() === false -->
                     <button class="btn btn-sm" data-bind="visible:AllowEdit, click:$parent.startEditMap"><i class="glyphicon glyphicon-pencil" ></i> @MemeMVC.Resource.Map.Admin.Button_Detail_Edit</button>
                     <button class="btn btn-sm" data-bind="visible:AllowRemove, click:$parent.removeMap" ><i class="glyphicon glyphicon-trash" ></i> @MemeMVC.Resource.Map.Admin.Button_Detail_Remove</button>
                    <!-- /ko -->
                    <!-- ko if: IsEdit() === true -->
                    <button class="btn btn-sm" data-bind="click:$parent.finishEditMap" ><i class="glyphicon glyphicon-ok" ></i> @MemeMVC.Resource.Map.Admin.Button_Detail_Save</button>
                    <button class="btn btn-sm" data-bind="click:$parent.cancelEditMap" ><i class="glyphicon glyphicon-remove"></i> @MemeMVC.Resource.Map.Admin.Button_Detail_Cancel</button>
                    <!-- /ko -->
                    <button class="btn btn-sm" data-bind="click: $parent.goBackToHome"><i class="glyphicon glyphicon-arrow-left"></i>@MemeMVC.Resource.Map.Admin.Button_Detail_Back</button>
                </div>
             </div>
         </form>
    </div>
</div>
@section popup{
}
@section scripts{
    @Html.Partial("_CreateJScript")
}

Implementation/branches/MemeMVC/MemeMVC/Views/Map/Detail1.cshtml
@{
    Layout = "~/Views/Shared/_MemeLayout.cshtml";    
}
<link id="base-style" href="~/Content/memeplugin/tip_cards.css" rel="stylesheet">
<!-- MAIN PANEL -->
<div id="main" role="main">

    

    <!-- MAIN CONTENT -->
    <div id="content"  data-bind="with: MapsVM">

        <div class="row">
            <div class="col-xs-12 col-sm-7 col-md-7 col-lg-4">
                <h1 class="project-title"><span data-bind="html: $root.ProjectName()"></span></h1>
            </div>
        </div>
        <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12" >
                <div class="controls">
                        <a class="btn btn-default" data-bind="click: startAddMap">
                            <i class="glyphicon glyphicon-plus" title="Add new map" >
                            </i>New Map</a>
                    </div>
            </div>
        </div>
                <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12" style="border-bottom: solid 1px #dddddd;">
                <!-- input: search field -->
                <div class="row">
                    <div class="col-xs-4 col-sm-4 col-md-4 col-lg-4"></div>
                    <div class="col-xs-8 col-sm-8 col-md-8 col-lg-8">
                           <div class="header-search pull-left " style="padding-top:10px;">
                                <input type="text" placeholder="Find map" id="search-fld"  data-bind="value:GetSearchParam('SearchCode').Value"/>
                                <button data-bind="click:searchMaps" style="padding-top:8px;">
                                    <i class="fa fa-search"></i>
                                </button>
                            </div>
                        <div class="pull-right" data-bind="with:Paging">
                            <ul class="pagination">
                                <li><a data-bind="html:'@MemeMVC.Resource.Map.Admin.Text_TotalItems <b>' + TotalItems() + '</b> @MemeMVC.Resource.Map.Admin.Text_ItemName &nbsp;&nbsp; &nbsp; &nbsp; &nbsp; @MemeMVC.Resource.Map.Admin.Text_Page <b>'+ PageIndex() + '/' + TotalPages() +'</b>'"></a></li>
                                <li data-bind="css:{disabled:PageIndex()==0}"><a data-bind="click:$parent.gotoPrevPage">&laquo;</a></li>
                                <!-- ko foreach:Pages -->
                                <li data-bind="css:{active:$parent.PageIndex()==$data}"><a data-bind="html:$data ,click:$parents[1].gotoPage"></a></li>
                                <!-- /ko -->
                                <li data-bind="css:{disabled:PageIndex()>=TotalPages()}"><a data-bind="click:$parent.gotoNextPage">&raquo;</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
                <!-- end input: search field -->
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <ul id="maplist" class="tips"  data-bind="foreach: ArrMap">
                    <li class="hiddentip">                        
                        <div class="tip" data-bind="attr: {id:'tip'+ $index()}">
                            <div style="height:200px;">
                                <!-- ko if: IsEdit() === false -->
                                <a class="titlelink" data-bind="attr: {href: '@Url.Action("Detail", "Map")' + '/'+ MapID() }">
                                    <span data-bind="html: Name"></span></a>
                                <!-- /ko -->
                                <!-- ko if: IsEdit() === true -->
                                 <input data-bind="value: Name" />
                                <!-- /ko -->
                                <p>
                                    <b>Last Access</b> <br />
                                    <span data-bind="html:LastAccessDate"></span> <br />
                                </p>
                                <div style="height:30px; position:absolute;bottom:0px;">
                                <!-- ko if: IsEdit() === false -->
                                 <button class="btn btn-sm" data-bind="visible:AllowEdit, click:$parent.startEditMap" title="@MemeMVC.Resource.Map.Admin.Tooltip_Edit"><i class="glyphicon glyphicon-pencil"></i></button>
                                 <button class="btn btn-sm" data-bind="visible:AllowRemove, click:$parent.removeMap" title="@MemeMVC.Resource.Map.Admin.Tooltip_Remove"><i class="glyphicon glyphicon-trash"></i></button>
                                 <!-- /ko -->
                                <!-- ko if: IsEdit() === true -->
                                <button class="btn btn-sm" data-bind="click:$root.finishEditMap" title="@MemeMVC.Resource.Map.Admin.Tooltip_Save" ><i class="glyphicon glyphicon-ok"></i></button>
                                <button class="btn btn-sm" data-bind="click:$parent.cancelEditMap" title="@MemeMVC.Resource.Map.Admin.Tooltip_Cancel"><i class="glyphicon glyphicon-remove"></i></button>
                                <!-- /ko -->
                                </div>
                            </div>
                            
                        </div>
                    </li>

                </ul>
            </div>
        </div>
    </div>
    <!-- END MAIN CONTENT -->

</div>
<!-- END MAIN PANEL -->
@section popup{
}
@section scripts{


    @Html.Partial("_IndexJScript")
}

Implementation/branches/MemeMVC/MemeMVC/Views/Map/DetailList.cshtml
@{
    Layout = "~/Views/Shared/_MemeLayout.cshtml";    
}

<!-- MAIN PANEL -->
<div id="main" role="main">
    <!-- MAIN CONTENT -->
    <div id="content">
        <div class="row">
             <div class="col-md-12">
                    <div class="pagetitle">
                        <h1 class="page-title txt-color-blueDark"><i class="fa-fw fa fa-file"></i><span data-bind="html: $root.MapName()"></span></h1>
                    </div>
             </div>
         </div>
        <br /><br /><br />
        <div class="row">
            <div class="col-md-12" >
                <table class="table table-striped ">
                    <thead>
                        <tr>
                            <td>
                                <button class="btn" data-bind="visible:$root.ParentVertex()!=null,click:$root.loadVertexByParent" ><i class="glyphicon glyphicon-arrow-left"></i></button>
                            </td>
                        </tr>
                    </thead>
                    <tbody data-bind="foreach: $root.ArrDisplayVertex">
                        <tr> <td> <span data-bind="html:Name"></span> <button class="btn" data-bind="visible: NumChild()>0,click:$root.loadVertexByIn" ><i class="glyphicon glyphicon-arrow-right"></i></button></td></tr>
                    </tbody>
                    <tfoot>
                        <tr>
                            <td>
                                 <ul class="pagination">
                                <li data-bind="css:{disabled:$root.CurrentLevel()==0},click:function(){ if($root.CurrentLevel()==0)return false; $root.loadVertexByLevel($root.CurrentLevel() -1);}"><a>&laquo;</a></li>
                                <li data-bind="css:{active:$root.IsLoadByLevel()}, click:function(){ $root.loadVertexByLevel($root.CurrentLevel());}"><a data-bind="html:CurrentLevel"></a></li>
                                <li data-bind="css:{disabled:$root.ArrDisplayVertex().length == 0|| $root.IsLoadByLevel()==false},click:function(){ if($root.ArrDisplayVertex().length == 0)return false; $root.loadVertexByLevel($root.CurrentLevel() + 1);}"><a>&raquo;</a></li>
                            </ul>
                            </td>
                        </tr>
                    </tfoot>
                </table>
            </div>
        </div>
    </div>
    <!-- END MAIN CONTENT -->
</div>
<!-- END MAIN PANEL -->
@section popup{
}
@section scripts{
    @Html.Partial("_DetailListJScript")
}

Implementation/branches/MemeMVC/MemeMVC/Views/Map/Edit.cshtml
@{
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}
@section styleContent{
}
<div class="row">
    <div class="col-md-12" data-bind="with:$root.MapVM">
        <div class="row" data-bind="visible:Processing().GetProcessing('Map')()" >
           <div class="col-md-6 col-md-offset-6" style="position:absolute">
               <img src="~/Images/kloading.gif" alt="Loading ..." />
           </div>
        </div>
        <form id="formMap" class="form-horizontal" role="form" data-bind="with:Map">
             <div class="row titleholder">
                <div class="col-md-6">
                      <div class="moduletitle">
                          <span>@MemeMVC.Resource.Map.Admin.Title_Edit</span>
                      </div>
                </div>
                <div class="pull-right" data-bind="visible:$root.Processing().Completed()==100">
                    <!-- ko if: IsEdit() === false -->
                     <button class="btn btn-sm" data-bind="visible:AllowEdit, click:$parent.startEditMap"><i class="glyphicon glyphicon-pencil" ></i> @MemeMVC.Resource.Map.Admin.Button_Detail_Edit</button>
                     <button class="btn btn-sm" data-bind="visible:AllowRemove, click:$parent.removeMap" ><i class="glyphicon glyphicon-trash" ></i> @MemeMVC.Resource.Map.Admin.Button_Detail_Remove</button>
                    <!-- /ko -->
                    <!-- ko if: IsEdit() === true -->
                    <button class="btn btn-sm" data-bind="click:$parent.finishEditMap" ><i class="glyphicon glyphicon-ok" ></i> @MemeMVC.Resource.Map.Admin.Button_Detail_Save</button>
                    <button class="btn btn-sm" data-bind="click:$parent.cancelEditMap" ><i class="glyphicon glyphicon-remove"></i> @MemeMVC.Resource.Map.Admin.Button_Detail_Cancel</button>
                    <!-- /ko -->
                    <button class="btn btn-sm" data-bind="click: $parent.goBackToHome"><i class="glyphicon glyphicon-arrow-left"></i>@MemeMVC.Resource.Map.Admin.Button_Detail_Back</button>
                </div>
             </div>
             @Html.Partial("_FormMap")
             <div class="row titleholder">
                <div class="col-md-6">
                </div>
                <div class="pull-right" data-bind="visible:$root.Processing().Completed()==100">
                    <!-- ko if: IsEdit() === false -->
                     <button class="btn btn-sm" data-bind="visible:AllowEdit, click:$parent.startEditMap"><i class="glyphicon glyphicon-pencil" ></i> @MemeMVC.Resource.Map.Admin.Button_Detail_Edit</button>
                     <button class="btn btn-sm" data-bind="visible:AllowRemove, click:$parent.removeMap" ><i class="glyphicon glyphicon-trash" ></i> @MemeMVC.Resource.Map.Admin.Button_Detail_Remove</button>
                    <!-- /ko -->
                    <!-- ko if: IsEdit() === true -->
                    <button class="btn btn-sm" data-bind="click:$parent.finishEditMap" ><i class="glyphicon glyphicon-ok" ></i> @MemeMVC.Resource.Map.Admin.Button_Detail_Save</button>
                    <button class="btn btn-sm" data-bind="click:$parent.cancelEditMap" ><i class="glyphicon glyphicon-remove"></i> @MemeMVC.Resource.Map.Admin.Button_Detail_Cancel</button>
                    <!-- /ko -->
                    <button class="btn btn-sm" data-bind="click: $parent.goBackToHome"><i class="glyphicon glyphicon-arrow-left"></i>@MemeMVC.Resource.Map.Admin.Button_Detail_Back</button>
                </div>
             </div>
        </form>
    </div>
</div>
@section popup{
}
@section scripts{
    @Html.Partial("_EditJScript")
}

Implementation/branches/MemeMVC/MemeMVC/Views/Map/_ArrPageMap.cshtml
<div class="row" data-bind="with:MapsVM">
    <div class="col-md-12">
        <div class="row">
            <div class="col-md-12">
                <div class="dark">
                    <div class="row">
                        <div class="col-md-5">
                            <span>@MemeMVC.Resource.Map.Admin.Title </span>
                        </div>
                        <div class="col-md-3">
                            <div class="input-group">
                                <input type="text" class="form-control" placeholder="@MemeMVC.Resource.Map.Admin.PlaceHolder_Search" data-bind="value:SearchCode" />
                                <div class="input-group-btn">
                                    <button class="btn btn-default" type="button" data-bind="click:searchMaps" style="margin-top:4px;">
                                        <i class="glyphicon glyphicon-search"></i>@MemeMVC.Resource.Map.Admin.Button_Search
                                    </button>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-4">
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div data-bind="visible:Processing().GetProcessing('Maps')" class="row" style="position: absolute">
            <div class="col-md-5 col-md-offset-5">
                <img src="~/Images/kloading.gif" alt="Loading..." />
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                @Html.Partial("_TableMap")
            </div>
        </div>
    </div>
</div>

Implementation/branches/MemeMVC/MemeMVC/Views/Map/_FormMap.cshtml
<!-- ko if: IsEdit()===false -->
        <div class="form-group">
            <label for="ctrlProjectID" class="col-md-2 control-label">@MemeMVC.Resource.Map.Admin.Label_Table_ProjectID</label>
            <div class="col-md-10">
                <span  data-bind="html:ProjectName" ></span>
            </div>
        </div>
        <div class="form-group">
            <label class="col-md-2 control-label">@MemeMVC.Resource.Map.Admin.Label_Table_Name</label>
            <div class="col-md-10">
                <span data-bind="html:Name" ></span>
            </div>
        </div>
        <div class="form-group">
            <label class="col-md-2 control-label">@MemeMVC.Resource.Map.Admin.Label_Table_Description</label>
            <div class="col-md-10">
                <span data-bind="html:Description" ></span>
            </div>
        </div>
<!-- /ko -->
<!-- ko if: IsEdit()===true -->
        <div class="form-group">
            <label for="ctrlProjectID" class="col-md-2 control-label">@MemeMVC.Resource.Map.Admin.Label_Table_ProjectID</label>
            <div class="col-md-10">
                <select id="ctrlProjectID" data-bind="options: $parent.ProjectsVM().ArrProject,optionsText:'Name',optionsValue:'ProjectID',optionsCaption:'@MemeMVC.Resource.Map.Admin.PlaceHolder_Table_ProjectID',value:ProjectID" class="form-control col-md-12" ></select>
            </div>
        </div>
        <div class="form-group">
            <label for="ctrlName" class="col-md-2 control-label">@MemeMVC.Resource.Map.Admin.Label_Table_Name</label>
            <div class="col-md-10">
                <input id="ctrlName" type="text" data-bind="value:Name" class="form-control col-md-12" />
            </div>
        </div>
        <div class="form-group">
            <label for="ctrlDescription" class="col-md-2 control-label">@MemeMVC.Resource.Map.Admin.Label_Table_Description</label>
            <div class="col-md-10">
                <input id="ctrlDescription" type="text" data-bind="value:Description" class="form-control col-md-12" />
            </div>
        </div>
<!-- /ko -->